//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANPRData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblANPRData
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string Lane { get; set; }
        public string PlateNo { get; set; }
        public string CountryCode { get; set; }
        public string Status { get; set; }
        public string PlateColour { get; set; }
        public string BackGroundColour { get; set; }
        public string Category { get; set; }
        public string PlateSize { get; set; }
        public byte[] PlateImage { get; set; }
        public string CImage { get; set; }
        public Nullable<int> x1 { get; set; }
        public Nullable<int> x2 { get; set; }
        public Nullable<int> x3 { get; set; }
        public Nullable<int> x4 { get; set; }
        public Nullable<int> y1 { get; set; }
        public Nullable<int> y2 { get; set; }
        public Nullable<int> y3 { get; set; }
        public Nullable<int> y4 { get; set; }
        public byte[] NumberPlate { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string Video { get; set; }
    }
}
