//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANPRData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblstate
    {
        public int Id { get; set; }
        public int CountryId { get; set; }
        public string State { get; set; }
    
        public virtual tblCountry tblCountry { get; set; }
    }
}
